### ISSUE TITLE
Switch out lambda user management from using client cert

### ISSUE THREAD

**Issue by limed** [mozilla-itcloud/maintenance-project#31]
With ldap moving the MDC1 the security team is not bringing over the ability to auth with client certificates which is how we auth to ldap to do our queries in AWS. Need to make sure that nubisproject/nubis-bastionsshkey is fixed to not use client certificates anymore. 

Once we remove that we will need to provide jabba with a list of the NAT EIP's for every account so that they can IP whitelist the LDAP VIP on their end.

```
09:38:09 jabba | how hard would it be to get a static IP for your ldap client that I can whitelist so we can ditch the client cert?
10:11:46 jabba | I need to shut down the client cert vip in the next two weeks
```

**Comment by mgreensmith** [comment]
```
jabba [8:37 AM]
hi, yes
there is a separate project to deprecate the CA that was used to manage/sign the client certificates
upon investigation, it was found that only 9 client certs were ever issued by the subCA that was for the ldap.mozilla.org client cert service, one of them belongs to the Nubis team, the other 8 were issued to cloudops/cloudservices
actually, it might not be 8
there were 2-3 belonging to dead projects
but anyway, only two customers exist
and the CA is gone
furthermore, with the move from scl3 to mdc1, the LDAP services are no longer behind zeus load balancers
the zeus load balancer was what handled all the SSL offloading and the client cert handling
in MDC1 all LDAP services are terminating their own SSL and using BGP for HA and load balancing
so, to continue the service, we would need a new CA, and learn/test handling client certs directly on the LDAP servers and there are limited resources to do this.
the entire mozilla root CA is gone as well, so we would need to outsource that portion, which costs money.
In addition, the IAM project happening in parallel is aimed at reducing the need for direct LDAP contact in general, as most web-auth can be handled by SSO now, rather than LDAP auth, and there is ongoing work to get other directory services that LDAP provides available through modern APIs
so for that reason, and the notion that there are only two customers of the service, and the costs involved, it was decided to not continue the ldap.mozilla.org service at all, in the long term
in the short term though, the technical limitation is mostly around the client cert portion
we will continue to operate the IP-whitelist portion for some time, until it seems more feasible to shut that one down, that one has a lot more customers, and is relatively easy to migrate to mdc1
mgreensmith [8:47 AM]
What's the timeline for deprecating `ldap.mozilla.org` entirely?
jabba [8:47 AM]
there isn't one yet. Once the dust settles from the mdc1 migration, I'll be able to assess that
mgreensmith [8:48 AM]
And LDAP is moving to mdc1 in two weeks? This is what's driving the timeline for deprecating client certs?
jabba [8:48 AM]
one of the limitations that the zeus load balancer gave us was the inability to see who is using the service clearly, because zeus connections all appear from the same IP
so I won't really know what the scope of the total decom will be until after the migration, and the migration is currently blocked by the client cert infra not being available in mdc1
yeah, I've been told that mid-to-late August is when SCL3 will be powered down completely
I will be out on PTO the first two weeks of august, so I need to get the ldap.mozilla.org service moved before July 31st
mgreensmith [8:49 AM]
OK. Are there options for access control other than IP whitelisting?
jabba [8:49 AM]
everything else LDAP related has been migrated already, this is the last thing
well, there is already extensive ACLs within LDAP on bind users, regular users, etc. that control what data can be seen by which users
inside the data center, we rely solely on those
it's only the public ldap.mozilla.org service that has the additional ip whitelist or client cert
mgreensmith [8:52 AM]
So, the reason that I ask is because our client IPs aren't static. They're elastic IPs provisioned against our NAT instances in each AWS account, and we periodically destroy and recreate those NATs when we roll our environments. Adding a manual whitelisting process (and delisting process) creates a bunch of friction for our account setup, which is entirely automated today.
So we're trying to brainstorm how to not regress our ability to provision accounts in an automated fashion.
jabba [8:53 AM]
I understand
mgreensmith [8:53 AM]
Frankly, this timeline is also a bit of a surprise. (edited)
jabba [8:54 AM]
do you know if there are ways in AWS to grant ACLs based on accounts?
like, if we in infosec set up a static ldap proxy in our account and then put in an ACL that says "any IP owned by cloudservices accounts can use this, block everything else" ?
doesn't know AWS very well
mgreensmith [8:55 AM]
Ah, ok, you said proxy, which was also something we were thinking about. :slightly_smiling_face:
jabba [8:55 AM]
like, if there were some way to just have one IP that is static that I can whitelist and then everything else uses that, then that should reduce the friction
mgreensmith [8:56 AM]
I think having a proxy in a datacenter doesn't serve much purpose (all our AWS IPs are dynamic), but running a proxy in AWS makes more sense for me.
jabba [8:56 AM]
I personally would also be fine not whitelisting and just allowing all connections directly, but then we rely solely on the LDAP ACLs, which haven't been fully pentested that I know of
so I don't think that solution would fly from a security standpoint
but my thought is if there could be a static host that just does a simple stunnel back to ldap.mozilla.org, and we can be certain that only hosts that mozilla owns can talk to the stunnel endpoint, then there aren't any moving parts
but I'm not sure of how this works in AWS
mgreensmith [8:58 AM]
Yeah, this is where we were going with the conversation as well. We run a proxy in AWS, it's IPs are known and whitelisted to  talk to LDAP, and then we can do ACLs against our proxy in an automated way via AWS security groups. (edited)
jabba [8:59 AM]
yes, I think that would be a good solution
mgreensmith [9:00 AM]
If we _had_ to, is it possible to keep the LDAP/zeus combo in SCL3 alive beyond the end of the month? This timeline is tough for us. (edited)
jabba [9:00 AM]
it might be possible. I will check with the SCL3 migration team when the absolute end date is, and I'm fine keeping it alive until then
mgreensmith [9:01 AM]
Awesome, thanks. OK, thanks for all this context, I appreciate it!
```

**Comment by mgreensmith** [comment]
jabba [8:37 AM]
hi, yes
there is a separate project to deprecate the CA that was used to manage/sign the client certificates
upon investigation, it was found that only 9 client certs were ever issued by the subCA that was for the ldap.mozilla.org client cert service, one of them belongs to the Nubis team, the other 8 were issued to cloudops/cloudservices
actually, it might not be 8
there were 2-3 belonging to dead projects
but anyway, only two customers exist
and the CA is gone
furthermore, with the move from scl3 to mdc1, the LDAP services are no longer behind zeus load balancers
the zeus load balancer was what handled all the SSL offloading and the client cert handling
in MDC1 all LDAP services are terminating their own SSL and using BGP for HA and load balancing
so, to continue the service, we would need a new CA, and learn/test handling client certs directly on the LDAP servers and there are limited resources to do this.
the entire mozilla root CA is gone as well, so we would need to outsource that portion, which costs money.
In addition, the IAM project happening in parallel is aimed at reducing the need for direct LDAP contact in general, as most web-auth can be handled by SSO now, rather than LDAP auth, and there is ongoing work to get other directory services that LDAP provides available through modern APIs
so for that reason, and the notion that there are only two customers of the service, and the costs involved, it was decided to not continue the ldap.mozilla.org service at all, in the long term
in the short term though, the technical limitation is mostly around the client cert portion
we will continue to operate the IP-whitelist portion for some time, until it seems more feasible to shut that one down, that one has a lot more customers, and is relatively easy to migrate to mdc1
mgreensmith [8:47 AM]
What's the timeline for deprecating `ldap.mozilla.org` entirely?
jabba [8:47 AM]
there isn't one yet. Once the dust settles from the mdc1 migration, I'll be able to assess that
mgreensmith [8:48 AM]
And LDAP is moving to mdc1 in two weeks? This is what's driving the timeline for deprecating client certs?
jabba [8:48 AM]
one of the limitations that the zeus load balancer gave us was the inability to see who is using the service clearly, because zeus connections all appear from the same IP
so I won't really know what the scope of the total decom will be until after the migration, and the migration is currently blocked by the client cert infra not being available in mdc1
yeah, I've been told that mid-to-late August is when SCL3 will be powered down completely
I will be out on PTO the first two weeks of august, so I need to get the ldap.mozilla.org service moved before July 31st
mgreensmith [8:49 AM]
OK. Are there options for access control other than IP whitelisting?
jabba [8:49 AM]
everything else LDAP related has been migrated already, this is the last thing
well, there is already extensive ACLs within LDAP on bind users, regular users, etc. that control what data can be seen by which users
inside the data center, we rely solely on those
it's only the public ldap.mozilla.org service that has the additional ip whitelist or client cert
mgreensmith [8:52 AM]
So, the reason that I ask is because our client IPs aren't static. They're elastic IPs provisioned against our NAT instances in each AWS account, and we periodically destroy and recreate those NATs when we roll our environments. Adding a manual whitelisting process (and delisting process) creates a bunch of friction for our account setup, which is entirely automated today.
So we're trying to brainstorm how to not regress our ability to provision accounts in an automated fashion.
jabba [8:53 AM]
I understand
mgreensmith [8:53 AM]
Frankly, this timeline is also a bit of a surprise. (edited)
jabba [8:54 AM]
do you know if there are ways in AWS to grant ACLs based on accounts?
like, if we in infosec set up a static ldap proxy in our account and then put in an ACL that says "any IP owned by cloudservices accounts can use this, block everything else" ?
doesn't know AWS very well
mgreensmith [8:55 AM]
Ah, ok, you said proxy, which was also something we were thinking about. :slightly_smiling_face:
jabba [8:55 AM]
like, if there were some way to just have one IP that is static that I can whitelist and then everything else uses that, then that should reduce the friction
mgreensmith [8:56 AM]
I think having a proxy in a datacenter doesn't serve much purpose (all our AWS IPs are dynamic), but running a proxy in AWS makes more sense for me.
jabba [8:56 AM]
I personally would also be fine not whitelisting and just allowing all connections directly, but then we rely solely on the LDAP ACLs, which haven't been fully pentested that I know of
so I don't think that solution would fly from a security standpoint
but my thought is if there could be a static host that just does a simple stunnel back to ldap.mozilla.org, and we can be certain that only hosts that mozilla owns can talk to the stunnel endpoint, then there aren't any moving parts
but I'm not sure of how this works in AWS
mgreensmith [8:58 AM]
Yeah, this is where we were going with the conversation as well. We run a proxy in AWS, it's IPs are known and whitelisted to  talk to LDAP, and then we can do ACLs against our proxy in an automated way via AWS security groups. (edited)
jabba [8:59 AM]
yes, I think that would be a good solution
mgreensmith [9:00 AM]
If we _had_ to, is it possible to keep the LDAP/zeus combo in SCL3 alive beyond the end of the month? This timeline is tough for us. (edited)
jabba [9:00 AM]
it might be possible. I will check with the SCL3 migration team when the absolute end date is, and I'm fine keeping it alive until then
mgreensmith [9:01 AM]
Awesome, thanks. OK, thanks for all this context, I appreciate it!

**Comment by tinnightcap** [comment]
IPs for ldap whitelist:

34.214.158.174, 52.26.11.25
34.213.69.143, 52.33.43.200
34.210.102.32, 54.148.16.24
34.216.191.128, 34.216.231.253
34.215.208.92, 34.210.220.226
34.208.12.235, 34.214.163.206
34.216.154.14, 52.24.122.144
34.214.4.111, 34.215.107.76
34.215.39.219, 34.210.100.100

**Comment by tinnightcap** [comment]
The updated function has been deployed to all accounts on our end. I will leave this open till the endpoint moves from scl3 to mdc2 just in case any issues arise.

**Comment by limed** [comment]
yup done
